# Generated by Django 2.2 on 2019-04-23 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('private_key', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=200)),
            ],
        ),
    ]
