# Generated by Django 2.2 on 2019-04-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnerbotserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
